### ISSUE TITLE
rsaDecode gives "Exception: Invalid Base64" for invalid input

### ISSUE THREAD

**Issue by Gothdo** [tekul/jose-jwt#15]
When I try to decode an invalid JWE, for example `=.`, `rsaDecode` gives `Exception: Invalid Base64`. I think it should return `Left (Base64Error "error message")` instead.

**Comment by tekul** [comment]
Thanks for the report. The problem was calling `either (fail ...)` where `fail` isn't actually the `Parser` version (I guess it's the Monad instance of `(->)` instead, which throws an exception (which definitely shouldn't happen). You probably won't get that specific error with the fix, though. Since I switched to using a parser to parse the JWT before trying to decode it, those errors are out of date. It will probably just return a generic BadCrypto error instead. I will probably add a `ParseError` in a more significant version change, but I don't want to break existing code.

**Comment by tekul** [comment]
I just pushed a 0.7.6 release, which has the fix. Thanks again for the report.
