### ISSUE TITLE
MonadRandom for decoding?

### ISSUE THREAD

**Issue by dustin** [tekul/jose-jwt#32]
Hi, I was wondering why `MonadRandom` is required for decoding.  Is it possible to remove that constraint (or perhaps document why it's necessary)?

**Comment by tekul** [comment]
Hi, if you mean the generic `decode` function in the `Jose.Jwt` module, then that is because of the blinder [used in RSA decryption](https://github.com/tekul/jose-jwt/blob/master/Jose/Jwe.hs#L168). If you don't need that then you can write a pure version with the subset of algorithms you need, or use one of the specific provided functions if you already know the algorithm.
